version: "3"
services:
 backend-app-001:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb-001
 mongodb-001:
    image: mongo:6.0-focal
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"